apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-app
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo-container
          image: alvishpatelhti/devops-demo-app:v1
          ports:
            - containerPort: 3000
